### ISSUE TITLE
No description or website provided.?

### ISSUE THREAD

**Issue by DonRichards** [canausa/vagrant-destroyer#1]
## What does this do?

The Github description is at the top of the repo is currently reading `No description or website provided.`

The name means little. I have no clue what this does and if I should install it.

**Comment by Mezzle** [comment]
https://rubygems.org/gems/vagrant-destroyer/versions/0.0.1

> If enable calls vagrant destroy following a vagrant up

**Comment by DonRichards** [comment]
I guess what I'm suggesting is for you to add the description to the Github description field so when new people are search Github they will know what your repo does.

**Comment by canausa** [comment]
At this time, I can not update any code in this repository. So this will not be fixed. I can not accept pull requests to update the documentation as well.
